### ISSUE TITLE
Support for whole market websockets?

### ISSUE THREAD

**Issue by MikeHibbert** [unicorn-data-analysis/unicorn-binance-websocket-api#28]
Hi 

I've been trying out this module and I'm aware that there is a limit to how many signs you can have in the URI

I was wondering if adding multiple websockets into the socket manager would be possible?

So far I've been breaking up my symbols into groups of 50 but once I get past creating the first websocket I get  errors saying:

ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.close_connection() done, defined at /home/mike/Documents/python/*******/lib/python3.6/site-packages/websockets/protocol.py:1114> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f11118670d8>()]>>

This is the code that creates the streams:

```
        MARKETS_SIZE = 50
        
        market_sections = [self.markets[x:x+MARKETS_SIZE] for x in range(0, len(self.markets), MARKETS_SIZE)]
        
        self.bm = BinanceWebSocketApiManager(self.process_unicorn_streams) 
        for market_section in market_sections:
            if self.bm.is_websocket_uri_length_valid(self.channels, market_section):
                stream_id = self.bm.create_stream(self.channels, market_section)
                self.unicorn_multi_stream_ids.append(stream_id)
```

**Comment by bithon** [comment]
Hi Mike!

I dont see a reason in your code.

But this is not a suggestion of an enhancement, you have problems running the code, so please open a "bug report" and provide the asked information. Then I can see if you are using the wrong websockets version and other infos that could help me to find the reason of this issue.

But i have one hint for you! Dont use "self.process_unicorn_streams", try the stream_buffer instead. This has a significant impact, because errors within the callback function are not shown in many cases, see here: https://github.com/unicorn-data-analysis/unicorn-binance-websocket-api/issues/18

I close this, please open a but report if you need! Thanks
